reponame: code.arista.io/efw/mfw_schema
description: |
  EFW settings JSON schema
users:
  maintainers:
    - abriles@arista.com
    - al.parker@arista.com
    - acooke@arista.com
    - avinash.dige@arista.com
    - crasmussen@arista.com
    - cblaise@arista.com
    - dhadarau@arista.com
    - donal@arista.com
    - iramasamy@arista.com
    - jphillips@arista.com
    - jsommerville@arista.com
    - k.skrzypczyn@arista.com
    - ksridhar@arista.com
    - sdelafond@arista.com
    - smitropoulos@arista.com
    - sumedha.game@arista.com
    - utkarsh.pratapsingh@arista.com
    - vishal.mane-ext@arista.com
    - vmishra@arista.com
  watchers:
    - bruce@arista.com
    - cmercer@arista.com
    - drush@arista.com
    - jcoffin@arista.com
    - manoj@arista.com
    - prashant.karunakaran@arista.com
    - sheck@arista.com
    - tkovalev@arista.com
x-bar:
  version: production
epoch: 1
